### ISSUE TITLE
balance udp traffic over the process pool

### ISSUE THREAD

**Issue by silviucpp** [processone/esip#12]
It might be a better idea to use a random distribution for the received udp packages instead the one that sends the packets from the same ip, port pair to the same process. 

In case all the traffic comes from a sip proxy (very common use to balance sip traffic) only one process is used to handle the traffic and all other 99 are idle.

```
get_proc_random() ->
    {_, _, MicroSecs} = os:timestamp(),
    get_proc((MicroSecs rem get_pool_size()) + 1).
```

Instead:
```
get_proc_by_hash(Source) ->
    N = erlang:phash2(Source, get_pool_size()) + 1,
    get_proc(N).
```

Provides a significant performance boost.

Silviu

**Comment by badlop** [comment]
Looks interesting! Can you send it as a PR?

**Comment by silviucpp** [comment]
@badlop please see the PR !

**Comment by badlop** [comment]
Merged, thanks!
