### ISSUE TITLE
Package not found in registry

### ISSUE THREAD

**Issue by arcusfelis** [processone/esip#7]
If we compile under rebar3, than Rebar3DepsFilter rewrites `deps` from git format to hex format.
Rebar3DepsFilter is too aggressive. Not all tags are present on Hex.

The transformation should be optional.

Error example:

```erlang
./rebar3 compile
Package not found in registry: fast_tls-1.0.17
```

**Comment by arcusfelis** [comment]
it's better to implement dependency resource plugin, which would check that packet exists on Hex, before rewriting. Or tries to download using both hex and git.
https://www.rebar3.org/docs/custom-dep-resources

**Comment by badlop** [comment]
> Not all tags are present on Hex.

Right, it may happen that a tag was not published to hex...

But this year, thanks to 7f84f39b45ce8c675ffc90cc5f6f28d167c29e58 , a tag gets immediately and automatically published to hex. This reduces the possibility that the problem appears.

> it's better to implement dependency resource plugin, which would check that packet exists on Hex, before rewriting. Or tries to download using both hex and git. https://www.rebar3.org/docs/custom-dep-resources

That feature is worth considering. That docs page returns 404. Is there any updated documentation page? Is there any example use out there?
